import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { AcceptanceMatrixResult } from './types.js';

function redactSecrets(text: string): string {
  return text
    .replace(/sk-[a-zA-Z0-9]*/g, '[REDACTED]')
    .replace(/Bearer\s+[\S]+/gi, 'Bearer [REDACTED]')
    .replace(/ghp_[a-zA-Z0-9]*/g, '[REDACTED]')
    .replace(/github_pat_[a-zA-Z0-9_-]*/g, '[REDACTED]');
}

export function writeAcceptanceMatrixReports(result: AcceptanceMatrixResult): void {
  const reportDir = result.report_dir;

  const sanitizedConfig = {
    ...result.config,
    sandbox_repo_path: '[REDACTED]',
    scenarios: result.config.scenarios.map((scenario) => {
      const copy = { ...scenario };
      if (copy.env) {
        // Remove scenario env from the report to avoid leaking secrets.
        copy.env = Object.fromEntries(Object.keys(copy.env).map((key) => [key, '[REDACTED]']));
      }
      return copy;
    }),
  };

  writeFileSync(
    join(reportDir, 'acceptance-matrix-result.json'),
    JSON.stringify(
      {
        ...result,
        config: sanitizedConfig,
      },
      null,
      2
    ),
    'utf-8'
  );

  const lines: string[] = [];
  lines.push('# Acceptance Matrix Report');
  lines.push('');
  lines.push(`- Started: ${result.started_at}`);
  lines.push(`- Finished: ${result.finished_at}`);
  lines.push(`- Duration: ${result.duration_ms}ms`);
  lines.push(`- Provider: ${result.config.provider}`);
  lines.push(`- Sandbox: ${result.config.sandbox_repo_slug ?? result.config.sandbox_repo_path}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Total scenarios: ${result.summary.total}`);
  lines.push(`- Passed: ${result.summary.passed}`);
  lines.push(`- Passed with caveats: ${result.summary.passed_with_caveats}`);
  lines.push(`- Failed: ${result.summary.failed}`);
  lines.push(`- Skipped: ${result.summary.skipped}`);
  lines.push(`- Orchestrator exit code: ${result.orchestrator_exit_code}`);
  lines.push('');
  lines.push('## Scenarios');
  lines.push('');

  for (const r of result.results) {
    lines.push(`### ${r.label} (${r.type})`);
    lines.push('');
    lines.push(`- Status: **${r.status}**`);
    lines.push(`- Expected: ${r.expected === true ? 'yes' : 'no'}`);
    if (r.classification) {
      lines.push(`- Classification: \`${r.classification}\``);
    }
    lines.push(`- Reason: ${redactSecrets(r.reason)}`);
    lines.push(`- Duration: ${r.duration_ms}ms`);
    if (r.block_path) {
      lines.push(`- Block: \`${r.block_path}\``);
    }
    if (r.state_path) {
      lines.push(`- State: \`${r.state_path}\``);
    }
    if (typeof r.commit_count_ahead === 'number') {
      lines.push(`- Commits ahead of ${r.block_path ? 'base' : 'base'}: ${r.commit_count_ahead}`);
      if (r.commits_ahead && r.commits_ahead.length > 0) {
        for (const sha of r.commits_ahead.slice(0, 5)) {
          lines.push(`  - \`${sha}\``);
        }
      }
    }
    if (r.resume) {
      lines.push(`- Resume no-op: exit_code=${r.resume.exit_code}, status=${r.resume.status}`);
      lines.push(`  - commits ahead before: ${r.resume.commit_count_ahead_before}`);
      lines.push(`  - commits ahead after: ${r.resume.commit_count_ahead_after}`);
      lines.push(`  - reason: ${redactSecrets(r.resume.reason)}`);
    }
    if (r.pr) {
      lines.push(`- PR created: ${r.pr.created ? 'yes' : 'no'}`);
      if (r.pr.number) lines.push(`  - Number: #${r.pr.number}`);
      if (r.pr.url) lines.push(`  - URL: ${r.pr.url}`);
      if (r.pr.reason) lines.push(`  - Reason: ${redactSecrets(r.pr.reason)}`);
    }
    lines.push(`- Evidence: \`${r.evidence_dir}\``);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('This report was generated by `npx tsx src/cli.ts acceptance-matrix <config.json>`.');
  lines.push('No token values are included in this report.');

  writeFileSync(
    join(reportDir, 'acceptance-matrix-report.md'),
    lines.join('\n'),
    'utf-8'
  );
}
