import type { ReliabilityClassification, ReliabilityClassificationMeta } from './types.js';

export function getClassificationMeta(classification: ReliabilityClassification): ReliabilityClassificationMeta {
  const meta = CLASSIFICATION_REGISTRY[classification];
  if (!meta) {
    return CLASSIFICATION_REGISTRY.UNKNOWN_FAILURE;
  }
  return meta;
}

export function isRepairPermitted(classification: ReliabilityClassification): boolean {
  return getClassificationMeta(classification).permitted === 'yes';
}

export function isExternalBlocker(classification: ReliabilityClassification): boolean {
  const permitted = getClassificationMeta(classification).permitted;
  return permitted === 'no';
}

export function isAmbiguousBlocker(classification: ReliabilityClassification): boolean {
  return getClassificationMeta(classification).permitted === 'human_required';
}

export const CLASSIFICATION_REGISTRY: Record<ReliabilityClassification, ReliabilityClassificationMeta> = {
  TEST_ASSERTION_FAILURE: {
    classification: 'TEST_ASSERTION_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'A test assertion failed with explicit expected/actual values.',
    requiredEvidence: ['failed test file', 'subtest name', 'expected/actual values', 'stack location', 'relevant source files'],
    stopCondition: 'Targeted test passes and full verification is green.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  TYPECHECK_FAILURE: {
    classification: 'TYPECHECK_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'TypeScript type checking failed with explicit error codes and locations.',
    requiredEvidence: ['compiler error codes', 'file and line', 'missing symbol or type mismatch'],
    stopCondition: 'npm run typecheck passes.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  BUILD_FAILURE: {
    classification: 'BUILD_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'The build step failed.',
    requiredEvidence: ['build error message', 'file and line when available'],
    stopCondition: 'npm run build passes.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  IMPORT_OR_MODULE_FAILURE: {
    classification: 'IMPORT_OR_MODULE_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'A module cannot be resolved or an import path is broken.',
    requiredEvidence: ['import statement', 'missing module name', 'file path'],
    stopCondition: 'Targeted check and build pass.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  MISSING_EXPORT: {
    classification: 'MISSING_EXPORT',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'A required export is missing from a module.',
    requiredEvidence: ['import site', 'module path', 'expected symbol name'],
    stopCondition: 'Importing test or build passes.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  WRONG_FUNCTION_BEHAVIOR: {
    classification: 'WRONG_FUNCTION_BEHAVIOR',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'A function returns or behaves incorrectly.',
    requiredEvidence: ['function location', 'expected behavior', 'actual behavior'],
    stopCondition: 'Targeted test passes.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  CONFIG_VALIDATION_FAILURE: {
    classification: 'CONFIG_VALIDATION_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'A JSON/YAML/config file fails validation or parsing.',
    requiredEvidence: ['config file path', 'validation error', 'schema constraint'],
    stopCondition: 'Config parses and validates.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  CLI_CONTRACT_FAILURE: {
    classification: 'CLI_CONTRACT_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'A CLI command branch or source-scan contract is violated.',
    requiredEvidence: ['CLI source branch', 'contract test expectation', 'changed command list'],
    stopCondition: 'Contract smoke tests pass.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  TESTING_SUMMARY_STALE: {
    classification: 'TESTING_SUMMARY_STALE',
    permitted: 'yes',
    maxAttempts: 1,
    description: 'TESTING_SUMMARY.md lock points to an older commit while non-summary files changed.',
    requiredEvidence: ['verify-testing-summary failure', 'current HEAD', 'changed files after Last verified commit'],
    stopCondition: 'verify-testing-summary passes locally and CI is green.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  DOCUMENTATION_CONTRACT_FAILURE: {
    classification: 'DOCUMENTATION_CONTRACT_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'A documentation contract test failed.',
    requiredEvidence: ['contract test expectation', 'documentation file path'],
    stopCondition: 'Documentation contract test passes.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  PROVIDER_BAD_OUTPUT: {
    classification: 'PROVIDER_BAD_OUTPUT',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'Provider output violated guardrails or schema.',
    requiredEvidence: ['guardrail violation reason', 'provider response excerpt'],
    stopCondition: 'Provider output passes validation and guardrails.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  ALLOWED_FILE_SCOPE_VIOLATION: {
    classification: 'ALLOWED_FILE_SCOPE_VIOLATION',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'Provider proposed changes outside allowed files.',
    requiredEvidence: ['allowed file list', 'proposed file list', 'guardrails result'],
    stopCondition: 'Provider restricts changes to allowed files.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  WINDOWS_PATH_OR_ENV_ISOLATION_FAILURE: {
    classification: 'WINDOWS_PATH_OR_ENV_ISOLATION_FAILURE',
    permitted: 'yes',
    maxAttempts: 2,
    description: 'Failure caused by Windows path separators, spaces, or leaked environment variables.',
    requiredEvidence: ['path value', 'environment variable name', 'child process command'],
    stopCondition: 'Targeted check passes on Windows/non-Windows.',
    finalVerdictWhenBlocked: 'NOT_FIXABLE',
  },
  CI_TIMEOUT: {
    classification: 'CI_TIMEOUT',
    permitted: 'no',
    maxAttempts: 0,
    description: 'CI workflow timed out or was cancelled.',
    requiredEvidence: ['workflow conclusion', 'timeout signal in logs'],
    stopCondition: 'Stop safely; require human or infrastructure action.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  CI_CANCELLED: {
    classification: 'CI_CANCELLED',
    permitted: 'no',
    maxAttempts: 0,
    description: 'CI workflow was cancelled externally.',
    requiredEvidence: ['workflow conclusion=cancelled'],
    stopCondition: 'Stop safely.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  GITHUB_RATE_LIMIT: {
    classification: 'GITHUB_RATE_LIMIT',
    permitted: 'no',
    maxAttempts: 0,
    description: 'GitHub API rate limit reached.',
    requiredEvidence: ['HTTP 403 with rate-limit headers', 'retry-after header'],
    stopCondition: 'Stop safely; wait for rate-limit reset.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  GITHUB_ACCESS_FAILURE: {
    classification: 'GITHUB_ACCESS_FAILURE',
    permitted: 'no',
    maxAttempts: 0,
    description: 'GitHub API request failed due to authentication or network.',
    requiredEvidence: ['HTTP 401/403', 'token presence check'],
    stopCondition: 'Stop safely; require token or permission fix.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  PUSH_PERMISSION_FAILURE: {
    classification: 'PUSH_PERMISSION_FAILURE',
    permitted: 'no',
    maxAttempts: 0,
    description: 'Git push rejected due to missing write permission.',
    requiredEvidence: ['git push stderr', 'remote 403'],
    stopCondition: 'Stop safely; require repository permission fix.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  PROVIDER_AUTH_FAILURE: {
    classification: 'PROVIDER_AUTH_FAILURE',
    permitted: 'no',
    maxAttempts: 0,
    description: 'AI provider rejected the request due to authentication.',
    requiredEvidence: ['HTTP 401 from provider', 'token presence check'],
    stopCondition: 'Stop safely; require API key fix.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  PROVIDER_RATE_LIMIT: {
    classification: 'PROVIDER_RATE_LIMIT',
    permitted: 'no',
    maxAttempts: 0,
    description: 'AI provider rate limit reached.',
    requiredEvidence: ['HTTP 429 from provider'],
    stopCondition: 'Stop safely; wait for provider reset.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  NETWORK_TRANSIENT: {
    classification: 'NETWORK_TRANSIENT',
    permitted: 'no',
    maxAttempts: 0,
    description: 'Transient network failure.',
    requiredEvidence: ['timeout', 'connection reset', 'DNS failure'],
    stopCondition: 'Stop safely; retry requires human trigger.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  WORKFLOW_INFRA_FAILURE: {
    classification: 'WORKFLOW_INFRA_FAILURE',
    permitted: 'no',
    maxAttempts: 0,
    description: 'GitHub Actions infrastructure failure unrelated to code.',
    requiredEvidence: ['runner failure', 'service unavailable'],
    stopCondition: 'Stop safely; require infrastructure recovery.',
    finalVerdictWhenBlocked: 'EXTERNAL_BLOCKER',
  },
  REQUIREMENTS_AMBIGUOUS: {
    classification: 'REQUIREMENTS_AMBIGUOUS',
    permitted: 'human_required',
    maxAttempts: 0,
    description: 'Failure cause is clear but the correct fix depends on product intent.',
    requiredEvidence: ['multiple valid fixes possible', 'mission scope ambiguity'],
    stopCondition: 'Stop for human decision.',
    finalVerdictWhenBlocked: 'AMBIGUOUS_BLOCKER',
  },
  FIX_REQUIRES_FORBIDDEN_FILE: {
    classification: 'FIX_REQUIRES_FORBIDDEN_FILE',
    permitted: 'human_required',
    maxAttempts: 0,
    description: 'Repair requires modifying a forbidden file.',
    requiredEvidence: ['proposed file outside allowed scope', 'denied_files list'],
    stopCondition: 'Stop for human approval of scope change.',
    finalVerdictWhenBlocked: 'AMBIGUOUS_BLOCKER',
  },
  FIX_REQUIRES_MIGRATION: {
    classification: 'FIX_REQUIRES_MIGRATION',
    permitted: 'human_required',
    maxAttempts: 0,
    description: 'Repair requires a breaking migration or schema change.',
    requiredEvidence: ['schema change required', 'breaking API surface'],
    stopCondition: 'Stop for human migration planning.',
    finalVerdictWhenBlocked: 'AMBIGUOUS_BLOCKER',
  },
  FIX_REQUIRES_SECRET: {
    classification: 'FIX_REQUIRES_SECRET',
    permitted: 'human_required',
    maxAttempts: 0,
    description: 'Repair would require embedding or exposing a secret.',
    requiredEvidence: ['secret-like value required in patch'],
    stopCondition: 'Stop immediately; never commit secrets.',
    finalVerdictWhenBlocked: 'AMBIGUOUS_BLOCKER',
  },
  FIX_REQUIRES_DESTRUCTIVE_ACTION: {
    classification: 'FIX_REQUIRES_DESTRUCTIVE_ACTION',
    permitted: 'human_required',
    maxAttempts: 0,
    description: 'Repair requires deleting data, branches, workflows or other destructive action.',
    requiredEvidence: ['destructive operation in proposed fix'],
    stopCondition: 'Stop for human approval.',
    finalVerdictWhenBlocked: 'AMBIGUOUS_BLOCKER',
  },
  UNKNOWN_FAILURE: {
    classification: 'UNKNOWN_FAILURE',
    permitted: 'human_required',
    maxAttempts: 0,
    description: 'Failure cannot be classified with available evidence.',
    requiredEvidence: ['log excerpt', 'workflow metadata'],
    stopCondition: 'Stop for human diagnosis.',
    finalVerdictWhenBlocked: 'AMBIGUOUS_BLOCKER',
  },
};
