import type { MvpRunTaskConfig } from './types.js';

export interface MvpRunFakeResponseArrays {
  kimi: (string | undefined)[];
  reviewer: (string | undefined)[];
  fixKimi: (string | undefined)[];
  secondReviewer: (string | undefined)[];
}

function fileUpdate(path: string, content: string): string {
  return JSON.stringify({
    mode: 'file_update',
    files: [{ path, content }],
    notes: `Update ${path}`,
  });
}

function acceptedReview(summary: string): string {
  return JSON.stringify({
    decision: 'accepted',
    confidence: 'high',
    blocking_issues: [],
    non_blocking_issues: [],
    review_summary: summary,
    fix_task: null,
    next_action: 'advance_to_next_task',
  });
}

export function buildMvpRunFakeResponses(tasks: MvpRunTaskConfig[]): MvpRunFakeResponseArrays {
  const kimi: string[] = [];
  const reviewer: string[] = [];
  const fixKimi: (string | undefined)[] = [];
  const secondReviewer: (string | undefined)[] = [];

  for (const task of tasks) {
    const targetFile = task.allowed_files[0];
    const content = `# ${task.title}\n\nGenerated by MVP run fake provider for task ${task.id}.\n`;
    kimi.push(fileUpdate(targetFile, content));
    reviewer.push(acceptedReview(`Task ${task.id} accepted`));
    fixKimi.push(undefined);
    secondReviewer.push(undefined);
  }

  return { kimi, reviewer, fixKimi, secondReviewer };
}
