import type { CoderProvider, CoderTaskInput, CoderResult, ProviderId } from '../provider-types.js';

export interface FakeCoderOptions {
  taskResponse?: CoderResult;
  fixResponse?: CoderResult;
}

export function createFakeCoderProvider(options: FakeCoderOptions = {}): CoderProvider {
  const defaultResult: CoderResult = {
    summary: 'fake coder result',
    files: [{ path: 'src/fake.ts', content: 'console.log("fake");\n' }],
    notes: 'generated by fake coder',
  };

  return {
    id: 'fake' as ProviderId,
    role: 'coder',
    async runTask(_input: CoderTaskInput): Promise<CoderResult> {
      return options.taskResponse ?? defaultResult;
    },
    async runFix(_input: CoderTaskInput): Promise<CoderResult> {
      return options.fixResponse ?? defaultResult;
    },
  };
}
