import type { CoderProvider, CoderTaskInput, CoderResult, ProviderId } from '../provider-types.js';

export interface FakeCoderOptions {
  taskResponse?: CoderResult;
  fixResponse?: CoderResult;
  taskResponses?: CoderResult[];
  fixResponses?: CoderResult[];
  taskResponseIndex?: number;
  fixResponseIndex?: number;
  onTaskInput?: (input: CoderTaskInput) => void;
  onFixInput?: (input: CoderTaskInput) => void;
}

export function createFakeCoderProvider(options: FakeCoderOptions = {}): CoderProvider {
  const defaultResult: CoderResult = {
    summary: 'fake coder result',
    files: [{ path: 'src/fake.ts', content: 'console.log("fake");\n' }],
    notes: 'generated by fake coder',
  };

  let taskIndex = 0;
  let fixIndex = 0;

  function nextTaskResult(): CoderResult {
    if (options.taskResponses && options.taskResponses.length > 0) {
      const idx = options.taskResponseIndex ?? 0;
      const result = options.taskResponses[idx % options.taskResponses.length];
      options.taskResponseIndex = idx + 1;
      return result;
    }
    return options.taskResponse ?? defaultResult;
  }

  function nextFixResult(): CoderResult {
    if (options.fixResponses && options.fixResponses.length > 0) {
      const idx = options.fixResponseIndex ?? 0;
      const result = options.fixResponses[idx % options.fixResponses.length];
      options.fixResponseIndex = idx + 1;
      return result;
    }
    return options.fixResponse ?? defaultResult;
  }

  return {
    id: 'fake' as ProviderId,
    role: 'coder',
    async runTask(input: CoderTaskInput): Promise<CoderResult> {
      options.onTaskInput?.(input);
      return nextTaskResult();
    },
    async runFix(input: CoderTaskInput): Promise<CoderResult> {
      options.onFixInput?.(input);
      return nextFixResult();
    },
  };
}
