import type { CoderProvider, CoderTaskInput, CoderResult, ProviderId } from '../provider-types.js';

export interface FakeCoderOptions {
  taskResponse?: CoderResult;
  fixResponse?: CoderResult;
  taskResponses?: CoderResult[];
  fixResponses?: CoderResult[];
}

export function createFakeCoderProvider(options: FakeCoderOptions = {}): CoderProvider {
  const defaultResult: CoderResult = {
    summary: 'fake coder result',
    files: [{ path: 'src/fake.ts', content: 'console.log("fake");\n' }],
    notes: 'generated by fake coder',
  };

  let taskIndex = 0;
  let fixIndex = 0;

  function nextTaskResult(): CoderResult {
    if (options.taskResponses && options.taskResponses.length > 0) {
      const result = options.taskResponses[taskIndex % options.taskResponses.length];
      taskIndex++;
      return result;
    }
    return options.taskResponse ?? defaultResult;
  }

  function nextFixResult(): CoderResult {
    if (options.fixResponses && options.fixResponses.length > 0) {
      const result = options.fixResponses[fixIndex % options.fixResponses.length];
      fixIndex++;
      return result;
    }
    return options.fixResponse ?? defaultResult;
  }

  return {
    id: 'fake' as ProviderId,
    role: 'coder',
    async runTask(_input: CoderTaskInput): Promise<CoderResult> {
      return nextTaskResult();
    },
    async runFix(_input: CoderTaskInput): Promise<CoderResult> {
      return nextFixResult();
    },
  };
}
